FROM python:3.12-slim

RUN apt-get update \
    && apt-get install -y --no-install-recommends git libpq-dev build-essential \
    && rm -rf /var/lib/apt/lists/*

COPY requirements-dbt.txt /tmp/requirements-dbt.txt

RUN pip install --no-cache-dir -r /tmp/requirements-dbt.txt

WORKDIR /usr/app

ENTRYPOINT ["dbt"]
CMD ["--help"]